title: JAX Tutorials
author: Smit Lunagariya
description: JAX tutorials by Smit Lunagariya

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

only_build_toc_files: true
execute:
  execute_notebooks: "cache"
  timeout: 600 # 10 minutes
  exclude_patterns:
    - '_static/*'

html:
  baseurl: https://smit-create.github.io/jax_tutorial


sphinx:
  extra_extensions: [sphinx_multitoc_numbering, sphinxext.rediraffe, sphinx_exercise, sphinx_togglebutton, sphinx.ext.intersphinx, sphinx_proof, sphinx_tojupyter]
  config:
    nb_render_image_options:
      width: 80%
    nb_code_prompt_show: "Show {type}"
    suppress_warnings: [mystnb.unknown_mime_type, myst.domains]
    # -------------
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_static_path: ['_static']
    html_theme_options:
      authors:
        - name: Smit Lunagariya
          url: https://smit-create.github.io/intro.html
      repository_url: https://github.com/Smit-create/jax_tutorial
      description: This website presents introductory lectures on JAX, designed and written by Smit Lunagariya.
      keywords: Python, JAX
      launch_buttons:
        notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
        binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
        colab_url                 : https://colab.research.google.com
        thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
    mathjax3_config:
      tex:
        macros:
          "argmax" : "arg\\,max"
          "argmin" : "arg\\,min"
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    rediraffe_redirects:
      index_toc.md: index.md
    tojupyter_static_file_path: ["_static"]
    tojupyter_target_html: true
    tojupyter_lang_synonyms: ["ipython", "ipython3", "python"]
    tojupyter_kernels:
      python3:
        kernelspec:
          display_name: "Python"
          language: python3
          name: python3
        file_extension: ".py"
    tojupyter_images_markdown: true
